In [2]:
import numpy as np

# The Basics

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
# get shape
#a.shape
b.shape

(2, 4)

In [8]:
#get dimension
#a.ndim
b.ndim

2

In [9]:
#get type
a.dtype

dtype('int32')

In [10]:
#get size
a.itemsize

4

In [11]:
#get total size (number of elements)
a.size

3

In [13]:
a.nbytes
b.nbytes

32

# Accessing/Changing specific elements,rows,columns etc

In [14]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [15]:
a.size

14

In [16]:
#get a specific element (row_no,column_no)
a[1,3]

11

In [17]:
a[1,-2]

13

In [18]:
#get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [19]:
#get a specific coloumn
a[:,2]

array([ 3, 10])

In [21]:
#getting a little more fancy [start_index:end_index:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [22]:
a[1,5 ]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [23]:
a[:,2]=5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [ ]:
3-d example

In [24]:
b= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [25]:
#get specific element (work outside in)
b[0,:,1]

array([2, 4])

In [26]:
#replace
b[0,1,1]=100
print(b)

[[[  1   2]
  [  3 100]]

 [[  5   6]
  [  7   8]]]


# Initializing Different Types of Arrays

In [27]:
#all 0s matrix
a=np.zeros(4)
b=np.zeros((2,3))
c=np.zeros((2,3,4))
print(a)
print(b)
print(c)

[0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [29]:
#all ones matrix
a=np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [30]:
#any other number(shape,number)
a=np.full((2,3),5)
print(a)

[[5 5 5]
 [5 5 5]]


In [31]:
np.full(a.shape,4)

array([[4, 4, 4],
       [4, 4, 4]])

In [32]:
#random decimal numbers
np.random.rand(4,2)

array([[0.28014371, 0.56219186],
       [0.17845912, 0.14298129],
       [0.49776282, 0.07198063],
       [0.73043906, 0.22180855]])

In [33]:
np.random.random_sample(a.shape)

array([[0.1297994 , 0.761181  , 0.83376081],
       [0.40242315, 0.8848807 , 0.66038466]])

In [34]:
#random integer values (number_range,size)
np.random.randint(7, size=(3,2))

array([[6, 3],
       [3, 2],
       [4, 1]])

In [35]:
#the identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
#repeat an array
arr = np.array([[1,2,3]])
r1= np.repeat(arr,4,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [42]:
#creating a pattern 
output = np.full((5,5),1)
#print(output)
z= np.zeros((3,3))
#print(z) 
z[1,1]=9

output[1:-1,1:-1]=z
print(output)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


# be careful when copying arrays

In [43]:
a = np.array([1,2,3])
b=a # 'b' is pointing to a 
b[0]=100 #it will change the element of 'a' also
print(b) 
print(a)

[100   2   3]
[100   2   3]


In [44]:
#copy function
a = np.array([1,2,3])
b=a.copy()
b[0]=100
print(b) 
print(a)

[100   2   3]
[1 2 3]


# Mathematics

In [46]:
a= np.array([1,2,3,4])
print(a)
print(a+2)
print(a-2)
print(a*2)
print(a/2)

[1 2 3 4]
[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]


In [47]:
a= np.array([1,2,3,4])
b= np.array([1,3,4,5])
a+b

array([2, 5, 7, 9])

a**2

In [49]:
#take trigonometric functions of array elements
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]


# linear algebra

In [50]:
a = np.ones((2,3))
b= np.full((3,2),2)
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [51]:
#find the determinant 
c= np.identity(3)
np.linalg.det(c)

1.0

# statistics

In [56]:
stats= np.array([[1,2,3],[4,5,6]])
print(np.min(stats))
print(np.min(stats, axis=1))#gives min of every row
print(np.max(stats))
print(np.max(stats, axis=1))

1
[1 4]
6
[3 6]


In [57]:
np.sum(stats)

21

In [58]:
np.sum(stats,axis=1)

array([ 6, 15])

# Reorganizing arrays

In [60]:
before = np.array([[1,2,3],[4,5,6]])
print(before)
after = before.reshape((3,2))
print(after)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [3]:
#vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
# horizontal stack
h1=np.zeros((2,3))
h2=np.ones((2,4))
np.hstack([h1,h2])

array([[0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1.]])

# Miscellaneous

In [ ]:
#loading data from file
filedata =np.genfromtext(file_name, delimiters=',')

# Boolean Masking and Advanced Indexing

In [ ]:
filedata>50
#gives an array of True or False based on checking each value of filedata whether it is > 50 or not

In [5]:
#index with a list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[0,2,4]]

array([1, 3, 5])

In [ ]:
np.any(filedata>50, axis=none)

In [ ]:
((filedata > 50) & (filedata <100))
-((filedata > 50) & (filedata <100)) #'-' implies not